### ISSUE TITLE
Scheduling events to change aggregate or saga state

### ISSUE THREAD

**Issue by rhyslbw** [CodeAdventure/space-cqrs#4]
- I have a `real world event` aggregate that has a start and end date
- This aggregate is created as the first step in a `job` saga
- When the event day starts (and ends) I wish to have the aggregate change state and the `job` saga to trigger commands and update it's own state via an event.

1. Do you have any similar scenarios in your domain?
2. Are you scheduling the aggregate events, which in my mind is the most logical solution, particularly in an event sourced system?
3. If not, what are you doing?

btw have you considered registering a https://gitter.im/ room for Space and architectural discussions around ddd and more complex UI patterns rather than them being lodged as issues?

**Comment by withinboredom** [comment]
In your messaging subsystem (like beanstalkd, azure topics, amazon sns, etc) you should be able to fire a delayed message. You can calculate the delay based on the time you want to work - the current time. When you receive that message, you can schedule the next one (for recurring sagas) and/or start work.

You can also use cron (if you are on linux) to fire the appropriate message as well...

**Comment by withinboredom** [comment]
for example, we opted to use cron (because delaying a message seems like a risky thing to some people). We store in the db all the sagas that need to be fired off (payment processing, sending transactional emails, etc) and then the cron job runs a job that then posts the message to start the sagas.

**Comment by rhyslbw** [comment]
Thanks @withinboredom

>We store in the db all the sagas that need to be fired off
Do you mean saga messages? If so it sounds like [vsivsi:job-collection](https://github.com/vsivsi/meteor-job-collection) is similar to what you are doing. I'm already using it elsewhere and it seems to be a good fit based on my requirements. The [1.1.0 release](https://github.com/vsivsi/meteor-job-collection#whats-new-in-v110) brings support for later.js and scheduling.

**Comment by rhyslbw** [comment]
Would you schedule the events in a Space.messaging.Controller when handling the `created` event?

**Comment by DominikGuzei** [comment]
Hey @rhyslbw, in my app I didn't have the need for this yet, but as @withinboredom suggested, I would also store saga references or create some infrastructure layer that dispatches specific (preconfigured) events at some point in the future.

Good idea btw, I created a gitter room for `space-cqrs`: https://gitter.im/CodeAdventure/space-cqrs

**Comment by rhyslbw** [comment]
Just wanted to finish this thread by summarising the [discussion](https://gitter.im/CodeAdventure/space-cqrs/archives/2015/05/21) @DominikGuzei and I had in the Gitter room

I was having reservations on the fact that there may have been logic leaking from the aggregate, but the model just needs to represent that a `RealWorldEvent` can start and end. In the real world the `event` does't just start by itself, time dictates that it is underway. In a system it's the infrastructure that manages time, so it is reasonable that it should be commanding the model to 'start' and 'end' when a queue job runs when a date is reached. The aggregate then records a domain event in the event store and mutates it's state. It's this event that the listeners react to, not the message sent from the infrastructure.
