### ISSUE TITLE
Snapshotting feature

### ISSUE THREAD

**Issue by rhyslbw** [CodeAdventure/space-cqrs#6]
This can be broken down into multiple parts.

1. Utilising snapshots when rehydrating the aggregate or process manager 
2. API for making a snapshot
3. Default configuration for out of the box functionality.

In a larger system we’d want to move the snapshot creation out to a dedicated process, so disabling the current process from creating snapshots via a configuration option should form part of the production release. 

Research:
http://blog.jonathanoliver.com/event-sourcing-and-snapshots/

**Comment by DominikGuzei** [comment]
Hey there!
The latest release includes a very simple, optional snapshotting solution that can be configured.
The default snapshotter does not yet support a dedicated process for it, but you could easily write a solution that supports this. The API contract between `Space.cqrs.Snapshotter` and `Space.cqrs.Repository` is very simple and can be extended in various ways :wink:
